
# (PART) EMA Catalogues {-}


# EMA Research within the APH Mental Health Consortium {#catalogue}

This chapter summarizes recent EMA research projects within the APH Mental Health consortium, as a guide to other researchers looking for nearby EMA-expertise and research collaboration. An overview of identified projects is presented in Table \@ref(tab:APHresearch). Detailed summaries are presented below. 

Table: (\#tab:APHresearch) Overview of EMA research in the APH MH consortium.

| Focus / PI          | Project                 | APH MH Organisation |
|:--------------------|:------------------------|:--------------------|
| **Depression**      |                         |                     |
| Bockting            | Imagine Your Mood       | AMC                 |
|                     | Stay Fine               |                     |
| Riper and Smit      | ICT4Depression          | VU / GGz InGeest    |
|                     | E-COMPARED              | VU / GGz InGeest    |
| Penninx and Lamers  | NESDA                   | VUmc / GGz InGeest  |
|                     | RADAR-CNS               | VUmc / GGz InGeest  |
| **Psychosomatic symptoms** |                  |                     |
| Knoop               | Chronic Fatigue study   | AMC                 |
| Snoek               | MERITS (type 1 diabetes)| VUmc                |
| Sprangers           | FAntasTIGUE (fatigue)   | AMC                 |
|                     | IMPACT (Heart failure)  | AMC                 |
| **Psychotic symptoms**|                       |                     |
| Van der Gaag        | TEMSTEM                 | VU                  |  
|                     | VRETp                   | VU                  |
| **Suicidal ideation**  |                      |                     |
| Van Ballegooijen    | CASPAR                  | VU                  |
| **Sleep**           |                         |                     |
| Van Someren         |                         | AMC / GGz InGeest   |
| **Symptom Networks**|                         |                     |
| De Geus         | VU-AMS                      | VU                  |


## Depression

### Bockting
\index{StayFine study}
\index{Imagine your Mood study}

*Prof. dr. Claudi Bockting* is affiliated with the AMC psychiatry department and the Rijksuniversiteit Groningen. Her group focuses on treatment and relapse prevention of (severe) depressive disorder and related common mental health disorders. In two studies of the group, EMA measures are included. 

| **Aspect**           | **Description**                                              | 
|:---------------------|:-------------------------------------------------------------|
| **Project team**     | Claudi Bockting, PhD; Yvonne Stikkelbroek, Phd; Gerard van Rijsbergen, PhD |
| **Organisation**     | AMC; Rijksuniversiteit Groningen |
| **Project(s)**       | 1) 'Imagine Your Mood' study (IYM; 2012-2017; @Slofstra2017): This was a three-arm RCT evaluating several relapse prevention strategies in remitted depressed patients.
|                      | 2) StayFine study (ongoing; http://stayfine.nl/): this RCT aims to evaluate a smartphone-based intervention to prevent relapse in young people (12-23 yrs.) with remitted anxiety or depression.
| **EMA Measures**     | In the IYM RCT, EMA items included mood, positive affect (PA, 5 items), negative affect (NA, 9 items) and mental imagery (2 items). Participants were prompted 10 times per day, 3 days a week, over a period of 8 weeks. Prompts were sent randomly within fixed time-intervals.  The VAS mood scale used (‘Please rate your current mood on a scale of 0 to 100’, on which 0 indicates ‘happy’, and 100 indicates ‘sad’), was shown to have a high positive predictive value without any false negatives at a cut-off score of 55 [@Vanrijsbergen2014]. Compared to the HAM-D17 and the IDS-SR, the VAS also was a better predictor of current relapse status, as measured by the SCID-1 interview (variance explained for VAS: 60%; HAM-D17: 49%; IDS-SR: 34%). 
|                      | In the StayFine RCT, EMA will be used to monitor outcomes (for three weeks) at six assessment periods (between baseline and 36-month follow-up). Additionally, Polar watches will be used to assess activity. |
| **Platforms used**   | Psymate, Roqua, ‘Imagine your mood’ app (custom development), Polar watches |
| **Contact**          | http://www.amc.nl/web/research-75/person-1/prof.-dr.-c.l.h.-bockting-phd.htm
|                      | http://claudibockting.com |


### Riper and Smit
\index{Moodbuster}
\index{ICT4Depression}
\index{E-COMPARED}

*Prof. dr. Heleen Riper* is affiliated with the department of clinical, neuro- and developmental psychology of the Vrije Universiteit and specialized mental health organisation GGz InGeest, Amsterdam. *Prof. dr. Jan Smit* is affiliated with the department of psychiatry of the Vrije Universiteit  Medical Center (VUmc) and GGz InGeest, Amsterdam. Riper and Smit have been driving forces behind the development of MoodBuster, a research platform for the delivery of online and blended psychotherapy, which has built-in, integrated EMA functionality.

| **Aspect**        | **Description**                                              | 
|:------------------|:-------------------------------------------------------------|
| **Project team**  | Heleen Riper, PhD, Jan Smit, PhD, and the MoodBuster consortium |
| **Organisation**  | Vrije Universiteit Amsterdam; GGZ inGeest (and other organisations)|
| **Project(s)**    | Moodbuster was developed in the European FP7 project “ICT4Depression” (@warmerdam2012; http://www.ict4depression.eu/), and applied in the Horizon 2020 FP7 EU-project “European COMPARative Effectiveness research on blended Depression treatment versus treatment-as-usual” (E-COMPARED; @Kleiboer2016; @kemmeren2016; http://www.e-compared.eu/), MoodBuster will also be used in the EU ImpleMentAll project (http://www.implementall.eu) and in several other clinical trials that are currently (October 2018) in preparation. |
| **EMA measures**  | In the ICT4Depression project, the MoodBuster platform included a complex set of active and passive EMA measures, including physiological sensors, accelerometers, wearables to measure sympathetic nervous system responses (chest strap and glove), and an Android EMA smartphone app. |
|                   | For the E-COMPARED study, the Moodbuster website and smartphone app were adapted to deliver (blended) treatment to patients with MDD, in 5 routine practice settings across Europe. A therapist portal was added, in order to allow therapists to monitor patients’ progress and send feedback messages. Smartphone- based EMA was used to asses sleep, mood, worrying, self-esteem, activities (2 items) and social contacts. Prompts were sent at a random time point between 10:00 and 22:00. At the beginning and during the final phase of treatment, patients received two additional prompts per day for one week. In the morning (around 10:00), sleep, worrying and self-esteem items were assessed. In the evening (around 22:00), these questions were repeated, along with the activity and social interaction items. Patients rated these EMA items on a visual analogue scale, ranging from 0 (low) to 10 (high).|
| **Platform used** | Moodbuster (http://www.moodbuster.eu) |
| **Contact**       | http://research.vu.nl/en/persons/heleen-riper | 
|                   | http://research.vumc.nl/en/persons/jan-smit |
|                   | http://research.vumc.nl/en/persons/lise-kemmeren |

### Penninx and Lamers
\index{NESDA}

Prof.dr. Brenda Penninx and Dr. Ir Femke Lamers are affiliated with the Department of Psychiatry, VU University Medical Center and GGz InGeest. Both are involved in two EMA studies: an EMA study in the context of the Netherlands study of Depression and Anxiety (NESDA; www.nesda.nl), of which Penninx is primary investigator, and a large international EU H2020-funded collaborative research project, in which a variety of active and passive measures are used (the 'Remote Assessment of Disease and Relapse - Central Nervous System'-project; RADAR-CNS; http://www.radar-cns.org).

#### NESDA EMA study

| **Aspect**     | **Description**                                              | 
|:---------------|:-------------------------------------------------------------|
| **Project team** | Femke Lamers, PhD, Brenda Penninx, PhD (VUmc), Hariette Riese, PhD (UMCG), with the NESDA consortium|
| **Organisation** | VUmc, GGZ inGeest, Amsterdam|
| **Project(s)**   | The main aim of NESDA (the Netherlands study of Depression and Anxiety) is to examine the long-term (eight-year) course and prognosis and co-morbidity of anxiety and depression, to improve quality of care and prevent chronicity [@Penninx2008]. Within the Wave 6 9-year follow-up of the NESDA study (2015 - 2017), a selected sample of NESDA participants with symptoms of depression and healthy controls (n = 384) was invited for an EMA diary /actigraphy study. |
| **EMA measures** | NESDA EMA study data was collected to explore the dynamic interplay between cognitions, emotions, behavior and environment in daily life of individuals, the feasibility of EMA in participants with affective disorders, and chronotype and diurnal patterns of activity in depressed versus non-depressed participants. EMA participants started within 31 days after the regular NESDA assessments (face-to-face interview and self-report measures). Participants could use their own smartphone (Android / IPhone) if they had sufficient data or access to WiFi for at least 80% of the two-week time period, and could borrow a phone if needed. To record the amount of physical activity during EMA monitoring, participants were also asked to wear an accelerometer (GENEActiv, 30Hz) on their non-dominant wrist, 24 hours a day, for two weeks. Recording started on the evening prior to the first EMA assessment and continued until the morning after the last assessment.|
|               | Participants were prompted five times a day, for two weeks, to complete a self-report questionnaire comprising approx. 31 items. Items (7-point Likert scale, ranging from 'not [at all]' to 'very') tapped 1) valance (unpleasant to pleasant) and arousal (calm to excited), 2) current state, symptoms of depression/anxiety, physical condition, 3) social context, 4) sleep, 5) daily uplifts/hassles, 6) activities, and 7) substance use. Examples of items were: "I feel down", "I feel cheerful" and "Where are you now" (e.g. at the neighbor's house). In addition, there was an addendum questionnaire with one item inquiring about questionnaire burden and an open-ended question for general comments on circumstances that might influence answers. The items on valance, arousal and current state have been used in a previous study; the Uncovering the Positive Potential of Emotional Reactivity (UPPER) study (@Bennik2015). The other items are inspired on earlier EMA studies, such as the work by Mehl and colleagues (@Mehl2012), van Os and colleagues (@Wichers2012) and studies performed at the Interdisciplinary Center of Psychopathology and Emotion regulation (ICPE), such as the Mood and Movement in Daily life (MOOVD) study (@Booij2015) |
| **Platform used** | RoQua (http://www.roqua.nl/), GENEActiv accelerometer |
| **Contact Information** | http://research.vumc.nl/en/persons/brenda-penninx |
|                         | http://research.vumc.nl/en/persons/femke-lamers   |
|                         | http://www.nesda.nl/ |


#### RADAR-CNS
\index{RADAR-CNS}

| **Aspect**       | **Description**                                              | 
|:-----------------|:-------------------------------------------------------------|
| **Project team** | Femke Lamers, PhD; Brenda Penninx, PhD; Sonia Difrancesco, MSc, and the RADAR consortium.  |
| **Organisation** | VUmc, GGZ inGeest |
| **Project** | The European (EU H2020-IMI) RADAR-CNS project (Remote Assessment of Disease and Relapse - Central Nervous System; http://www.radar-cns.org/) aims to study the potential of wearable devices and smartphone technology to help prevent and treat depression, multiple sclerosis and epilepsy. The project, which started in 2016, was designed to examine how remote measurement technologies can monitor and improve quality of life and psychological well-being of patients. Within this project, the VUmc/GGZ inGeest research site focuses on depression (RADAR-MDD), in collaboration with King's College, London (KCL). |
| |  Technical goals of the project are to 1) build an end-to-end open source system with generalized data aggregation capabilities, and 2) explore (technological aspects of) big data solutions. Clinical goals of the project are to 1) assess the feasibility of continuous monitoring of patients, and 2) predict disease onset or relapse with big data prevention and risk assessment approaches. |
| **EMA Measures** | Data are collected during a 2-year period, in which EMA will be activated every 6 weeks for 6 consecutive days. Active EMA outcomes include (variability in) sleep quality, levels of activity, social interactions, mood, cognitive performance and stress as possible predictors of the clinical course of participants. Passive EMA measures include location and movement (GPS; actigraphy), skin temperature, galvanic skin conductance, heart rate (-variability), voice recognition, social interaction data (call/message logs), and smartphone app usage patterns.|
| **Platform(s)**  | In the RADAR project, an comprehensive EMA platform is developed (the RADAR RMT application; see http://thehyve.nl/cases/radar-cns and http://github.com/RADAR-base); This platform focuses on classes of data rather than specific devices, to enhance modularity and adaptability, as new devices become available. The platform will be used to integrate and control data streams from an EMA smartphone app and several wearable device (including the [Empatica E4 Wristband](http://www.empatica.com/research/e4/), Pebble 2 Smart-watch, Biovotion VSM, Faros 180, and [Fitbit](http://www.fitbit.com/home). |
| **Contact**      | http://research.vumc.nl/en/persons/femke-lamers |
|                  | http://research.vumc.nl/en/persons/brenda-penninx |
|                  | http://www.radar-cns.org/ |


## Psychosomatic symptoms

### Knoop
\index{Chronic Fatigue}

Prof. dr Hans Knoop is professor of evidence-based psychological and behavioral interventions for medical conditions and somatic symptoms at department of Medical Psychology of the Amsterdam Medical Center (AMC). In 2015/2016, Knoop and colleagues ran an EMA study at the Expert Centre for Chronic Fatigue (ECCF; http://nkcv.nl/).

| **Aspect**     | **Description**                                                  | 
|:---------------|:-------------------------------------------------------------|
| **Project team** | Margreet Worm-Smeitink, MSc; Hans Knoop, PhD, in collaboration with Judith Rosmalen, PhD, Anne van Gils, MSc, Rei Monden, PhD, and others |
| **Organisation** | AMC |
| **Project** | The CFS EMA study was designed to investigate - through time-series analyses - whether there are differences in perpetuators of fatigue between individual patients. |
| **EMA measures | New patients attending the ECCF (n = 102) were asked to complete an e-diary, 5 times a day, for 2 weeks. The times were fixed in consultation with the participant, with a 3-hour break between each assessment. The e-diary assessed  fatigue, pain, anxiety, depression, activity (physical, mental, social), patients' focus on fatigue, fatigue catastrophising, self-efficacy, fear avoidance, and social incomprehension. Participants also wore an accelerometer (actigraphy) during the period when the self-reports were collected. The R 'auto-var' package was used to conduct network analyses. Results are forthcoming. Identified determinants of fatigue will used to personalize treatment of CFS-patients. |
| **Platform used** | RoQua (http://www.roqua.nl). Participants received a link to the (web-based) e-diary via an SMS to their personal smartphone. |  
| Contact Information | http://www.amc.nl/web/research-75/publications/prof.-dr.-j.a.-knoop.htm |
|                     | http://nkcv.nl/onderzoek/expert-centre-chronic-fatigue/ |


### Sprangers


#### FAntasTIGUE
\index{FAntasTIGUE}

| **Aspect**       | **Description**                                              | 
|:-----------------|:-------------------------------------------------------------|
| **Project team** | Mirjam Sprangers, PhD, in collaboration with Yvonne Goërtz, MSc; Zjala Ebadi (from July 2018), MSc, Melissa Thong, PhD, Daisy Janssen, MD, PhD, Jeanette Peters, PhD, Jan Vercoulen, PhD, Chris Burtin, MSc, Yvonne Meertens-Kerris, Arnold Coors, Jean Muris, MD, PhD, Emiel Wouters, MD, PhD, Judith Prins, PhD, and Martijn Spruit, PhD |
| **Organisation** | AMC (in collaboration with Ciro-Horn, Maastricht UMC, Radboud UMC, and Hasselt University) |
| **Project goals**| The FAntasTIGUE study examines fatigue in patients with chronic obstructive pulmonary disease (COPD; n = 400), by evaluating the course of fatigue, precipitating/perpetuating factors and hospitalization. A secondary aim is to identify diurnal fluctuations in fatigue, by using EMA in a sub-sample of participants (n = 40) [@Goertz2018].|
| **EMA measure**s | The project comprises four data collection periods (baseline, and 4, 8, and 12 month follow-up). During data collection periods, patients are provided with iPods, on which an EMA application will be pre-installed. Participants will be prompted 8 times a day, at random moments between 7:30 and 22:30, for 5 consecutive days, to answer 19 items (including nine contextual items). Measured concepts include fatigue, relaxed feeling, breathlessness, agitation, uncertainty, irritation, satisfaction, anxiety, feeling energetic, and feeling mentally fit. Items are rated on a 7-point Likert-scale, ranging from ‘Not at all’ to ‘Very much’. In addition, participants are asked to complete a morning questionnaire soon after they awaken to assess the quality of their sleep the previous night. Participants also complete an evening questionnaire, assessing the general perception of their day just before going to bed. During the EMA data collection period, patients will also be asked to wear an actigraph (activity monitor), 24 hours a day, for one week. |
| **Platform used**| Psymate (http://psymate.eu; see Chapter \@ref(ema-instruments-catalogue)) |
| **Contact**      | http://www.amc.nl/web/research-75/publications/prof.-dr.-m.a.g.-sprangers-publications.htm |

#### IMPACT
\index{IMPACT}

| **Aspect**        | **Description**                                              | 
|:------------------|:-------------------------------------------------------------|
| **Project team**  | Mirjam Sprangers, PhD, with Iris Hartog, MSc; Justine Netjes (until 2017), MSc; Tom Oreel, MSc; Pythia Nieuwkerk, PhD; Michael Scherer-Rath, PhD; José Henriques, MD, PhD; Hanneke van Laarhoven, MD, PhD  |
| **Organisation**  | AMC |
| **Project**       | The IMPACT project (http://www.impactonderzoek.nl/) is an NWO-funded study targeting the Quality of Life (QoL) of patients with multiple chronic morbidities, specifically those undergoing a cardiac intervention. The project aims to improve the conceptualization of QoL and enhance the sensitivity and comprehensiveness of its measurement by taking the trait-state distinction, contextual factors, and response shift into account). Participants are cardiac patients with comorbidities who were scheduled for elective percutaneous coronary intervention (PCI) or elective coronary artery bypass graft (CABG) (N = 320). In a sub-sample of participants, QoL is monitored through EMA (n = 37), to monitor QoL states. The study has a longitudinal design, with three EMA data collection periods: 1) pre-treatment, 2) two weeks after treatment for PCI patients or 3 months post-treatment for CABG patients, and 3) six months post-treatment. |
| **EMA measures**  | Participants are prompted to answer nine general and one evening questionnaire per day, for seven consecutive days. During the day, patients are beeped randomly between 7:30 and 22:30 to complete a 19-item questionnaire. Concepts measured include: positive mood (feeling energetic, relaxed feeling, cheerfulness, happy), negative mood (anxiety, sadness, irritation, worry), coronary artery disease symptoms (chest pain, tightness in chest, oppressive feeling on the chest), and general symptoms (tiredness, other types of pain, shortness of breath), and contextual items. Items are rated on a 7-point Likert-scale, ranging from ‘Not at all’ to ‘Very much’. Patients are also asked to complete an evening questionnaire just before they go to bed. The evening questionnaire has, besides the general questionnaire, an additional set of questions from the EQ-5D, and a question on the overall health state of the day. This item is rated on a visual analogue scale from 0 (worst) to 100 (best). Data will be analysed with vector auto-regressive models, using R. |
| **Platform used** | Psymate (http://psymate.eu); Participants are provided with iPods with a pre-installed EMA application, or , if they prefer, can use their own device. |
| **Contact**       | http://www.amc.nl/web/research-75/publications/prof.-dr.-m.a.g.-sprangers-publications.htm |


### Snoek
\index{MERITS study}

Frank Snoek is Professor of Medical Psychology, specialized in psycho-social diabetology. He heads the Diabetes Psychology Research Group (http://www.vumc.com/branch/diabetes-psychology/) and is consulting clinical psychologist for the VUmc Diabetes Center http://www.vumc.nl/afdelingen/diabetescentrum/). Snoek an co-workers use EMA to study the relationship between blood glucose variability and wellbeing.

| **Aspect**       | **Description**                                              | 
|:-----------------|:-------------------------------------------------------------|
| **Project team** | Frank J. Snoek, PhD, Maartje de Wit, PhD,  and others |
| **Organisation** | VUmc, AMC |
| **Project**      | In the MERITS study ('Momentary assessment of patient Experiences in Real life of Insulin Glargine 300 in Type 1 diabetes'), Snoek an co-workers use EMA to explorer whether a) blood glucose variability is associated with changes in wellbeing (mood / energy) during waking time, whether b)  switching to U-300 results in less glucose variability and translates into improved mood over time within patients, and whether c) if individual differences (profiles) can be distinguished with regard to the (strength of the) association between glucose variability and changes in mood. 
| **EMA measures** | Adult patients (N=70) with type 1 diabetes, will be (randomly) prompted to answer questions on mood (based on POMS questionnaire), diabetes distress, fear of hypoglycaemia and sleep. 
| **Platform used**| Ilumivu (http://ilumivu.com, see Chapter \@ref(ema-instruments-catalogue)) |
| **Contact**      | http://research.vumc.nl/en/persons/frank-snoek |
|                  | http://research.vumc.nl/en/persons/maartje-de-wit |


## Suicidal Ideation

### Van Ballegooijen
\index{CASPAR}

Dr. Wouter Van Ballegooijen is a post-doctoral researcher at the VU and GGZ inGeest, specialised in the use of information and communication technology in mental health care and suicide prevention. In the 'Continuous Assessment for Suicide Prevention And Research' study (CASPAR; @Nuij2018) Van Ballegooijen and colleagues use EMA to study pathways to suicidal behavior.

| **Aspect**       | **Description**                                              | 
|:-----------------|:-------------------------------------------------------------|
| **Project team** | Wouter van Ballegooijen, PhD; Chani Nuij, MSc.; Ad Kerkhof, PhD; Jan Smit, PhD; Heleen Riper, PhD |
| **Organisation** | Vrije Universiteit Amsterdam, VUmc, GGZ inGeest |
| **Project**      |  The 'Continuous Assessment for Suicide Prevention And Research' (CASPAR) study ([@Nuij2018) aims to evaluate the feasibility of mobile safety planning and daily mobile self-monitoring in routine care treatment for  for patients with major depression or dysthymia and suicide risk in mental health care. Feasibility will be operationalized in terms of uptake, usage, acceptability, usability and patient satisfaction. EMA data will be used to: (a) empirically validate hypothesized psychological processes and stages of suicide pathways, (b) identify individual pathways to suicidal behavior, and (c) profile (sub)types of suicidality. The project is expected to result in 1) an interactive smartphone-based safety plan that patients can access 24/7, 2) increased disease awareness of patients due to self-monitoring, and 3) input for the national and international field of mental health care by sharing our results and our data, ultimately contributing to more personalized interventions according to precision medicine principles, and more effective suicide prevention. |
| **EMA measures** | In the project, adult suicidal patients (N = 80) with major depression or dysthymia and suicide risk in mental health care will be prompted, three times a day, to answer eight self-report items (e.g. 'I feel sad') assessing mood, rumination, hopelessness, defeat, entrapment, burdensomeness, belongingness, impulsiveness, suicidal imagery and suicidal ideation. Items, which are based on existing questionnaires, such as the Patient Health Questionnaire (PHQ-9), are rated on a 7-point Likert-scale, ranging from 'Not at all' to 'Very much'. Results are presented to patients in graphs, which patients encouraged to discuss with their clinicians. In addition to active EMA data, location data are also gathered to assess movement patterns and daily rhythms. Planned variables also include accelerometer data and smartphone usage patterns. These data are not visible to study participants. |
| **Platform used**| Ilumivu (http://ilumivu.com, see Chapter \@ref(ema-instruments-catalogue)) |
| **Contact**      | http://research.vu.nl/en/persons/wouter-van-ballegooijen |
|                     | http://research.vu.nl/en/persons/chani-nuij |


## Psychotic symptoms

### Van der Gaag

*Prof. dr. Mark van der Gaag* is professor of Clinical Psychology at the VU University in Amsterdam, and  head of psychosis research at Parnassia, the Hague. He is specialised in the research and treatment of psychosis. In two recent RCTs, described below, Van der Gaag and colleagues used EMA outcomes to collect in-the-moment data.

#### TemStem
\index{TEMSTEM}

| **Aspect**       | **Description**                                              | 
|:-----------------|:-------------------------------------------------------------|
| **Team** | Mark van der Gaag, PhD, Alyssa Jongeneel, MSc, David van den Berg, PhD, Dorien Scheffers, MSc |
| **Organisation** | Vrije Universiteit Amsterdam, VUmc, GGZ inGeest, Parnassia Psychiatric Institute
| **Project** | The TemStem project focusses on people who suffer from hearing voices and are obstructed by them in their daily life. Study participants install an app that contains both an EMI and EMA function, which is designed to reduce distress and dysfunction caused by auditory verbal hallucinations [@jongeneel2018]. Components of the app include 1) coping: addressing verbal working memory phonological loop with a language task, thereby blocking the hearing of voices, 2) positive reinforcement: decreasing self-reported negative self-esteem themes, 3) treatment: reducing emotional response to memories associated with voices by taxing the auditory working memory during recall of negative auditory memories (as in EMDR therapy). The TemStem study aims to explore the effect of the app on distress and dysfunction in an RCT, specifically with regard to the effect of Temstem on frequency and severity of AVH. Additional analyses will focus on the identification of working mechanisms (predictors and mediators of effects), and the usability of Temstem.|
| **EMA measures** | TemStem users are encouraged to fill-in nine self-report items on a daily basis. Items tap: 1) hearing voices: 6 items (e.g. "Today, the voices were disturbing"), 2) mood, 3) self-esteem, 4) the use of Temstem ("I used Temstem today"). Items, which are rated on a 7-point Likert-scale, are based on existing EMA questionnaires. Results are presented to users in separate graphs, to support users in gaining insight in the pattern of AVH over time, or after use of Temstem. Stored variables include scores of vividness of AVH pre and post use of Temstem, data on application use (duration), used function (e.g. 'Silencing' function which focuses on coping, or 'Challenging' function which is based on dual tasking), and how users feel when they hear voices. Users can choose to provide additional information on age, gender, which county in the Netherlands they are currently located, how they found the app, and why they want to use it |
| **Platform used** | Temstem application was developed by Reframing Studio, in collaboration with Parnassia Psychiatric Institute and TU Delft. The app is available for IOS and Android. |
| **Contact** | http://research.vu.nl/en/persons/m-van-der-gaag |
|             | http://research.vu.nl/en/persons/alyssa-jongeneel |
|             | http://research.vu.nl/en/persons/dpg-van-den-berg |


### Van der Gaag: VRETp

| **Aspect**       | **Description**                                              | 
|:-----------------|:-------------------------------------------------------------|
| **Team**         | Mark van der Gaag, PhD, Roos Pot-Kolder, MSc, with others
| **Organisation** | Vrije Universiteit Amsterdam, VUmc, (in collaboration with UMC Groningen, Maastricht University) |
| **Project**      | In the context of a trail exploring the effect of virtual reality exposure therapy on social participation in people with a psychotic disorder (VRETp; n = 116, @pot2016), EMA data were collected to assess changes in social functioning and  paranoid ideation.
| **EMA measures** | EMA included momentary assessment of 1) Anxiety (one item, e.g. "I feel anxious"), 2) Perceived social threat (four items, e.g. "In this company, I feel accepted"), 3) Paranoia (three items, e.g. "I feel suspicious"), and 4) Time spent with others (max. three multiple choice items inquiring about type of company (nobody, family, non-family, etc.). These items were based on previous EMA work (e.g., @collip2011social). Participants were prompted 10 times a day, during 6 days. Anxiety, threat and paranoia items were rated on a 7-point Likert scale, ranging from 1 ("not at all") to 7 ("very"). Reports had to be completed within 15 min of the beep. To be included in the analysis, participants had to complete diary entries for at least one-third of the beeps (i.e., a minimum of 20 measurements). All 116 participants completed EMA measurements at baseline (mean number of completed self-assessments 46.1, SD 13.3), 96 participants completed the post-treatment assessment sufficiently (43.1, SD 10.1), and 87 participants completed the follow-up (43.2, SD 11.1). The trial results suggest that the addition of VR-CBT to standard treatment can reduce paranoid ideation and momentary anxiety in patients with a psychotic disorder [@pot2018].|
| **Platform used** | PsyMate (http://www.psymate.eu/, see Chapter \@ref(ema-instruments-catalogue)). Because the PsyMate application was not finished at the time of the trial, participants were provided with a small palmtop device for the duration of the study.|
| **Contact**       | http://research.vu.nl/en/persons/m-van-der-gaag |


## Sleep

### Van Someren
\index{Sleep}

*Prof. dr. Eus van Someren* is affiliated with the department of sleep and cognition of the Netherlands Institute for Neuroscience (http://herseninstituut.nl/), the Department of Psychiatry of VUmc and GGz InGeest, Amsterdam. His group focusses on the study of healthy and disturbed sleep, using neuro-imaging, actigraphy and EMA. 

| **Aspect**     | **Description**                                          | 
|:---------------|:-------------------------------------------------------------|
| **Team** | Eus van Someren, PhD (department head), with Bart te Lindert, MSc, Wisse van der Meijden, MSc, Tessa Blanken, MSc, Michele Colombo, PhD, Kim Dekker, MSc, Jeanne Leerssen, MSc, Rick Wassing, MSc.  |
| **Organisation** | VUmc, GGZ inGeest, the Netherlands Institute for Neuroscience |
| **Project(s)** | *Wisse van der Meijden* studies, among other things, the interplay between light, vigilance, and sleep. A recent study associated the post-illumination pupil response (PIPR) to blue light with multiple indices of sleep timing: a) a questionnaire on habitual lights-out time, sleep onset latency, and final wake-up time (Munich Chronotype Questionnaire, MTCQ [@Roenneberg2003]); b) a one-week sleep diary on actual wake/sleep times; and c) actigraphy. Actigraphy data were obtained using either a Philips Actiwatch Spectrum or a microelectromechanical accelerometer (Move II, Movisens GmbH). Data collection was set to 30Hz. Sleep onset and final wake-up time were estimated using an algorithm that is implemented in Matlab (http://github.com/btlindert/actant-1). Participants (adolescents and young adults, n = 71) with a later sleep timing had a stronger responsiveness to blue light. The mid-sleep timing estimates from sleep diaries and actigraphy shared 94.5% of their inter-individual variance [@Meijden2016]. | 
|                |  *Bart te Lindert* studies the effect of the environment on sleepiness, for example by measuring light, (skin) temperature, posture, and psychological variables. A recent study focused on the effect of light intensity on Liking, Wanting and mood in insomnia disorder. In a recent study, active and passive EMA were combined. EMA prompts were sent eight times a day, for one week. Prompts were timed at quasi-random intervals between 8:00 and 22:00. In addition, participants provided input after waking up and before bedtime. The interval between prompts ranged between 16 minutes and 3 hours. EMA consisted of 22 items. Liking and Wanting (6 items each), focused on taste or smell, bodily sensation, watching or listening, interactions with other, physical activity or being busy, and receiving something. Participants indicated whether they enjoyed and wanted these categories on a 0-100 VAS scale (ranging from not to very much). Mood items were derived from the Daytime Insomnia Symptom Scale (DISS, @buysse2007), which was developed specifically for EMA. Items focused on positive mood (5 items; relaxed, energetic, calm, happy, and efficient) and negative mood (5 items; anxious, stressed, tense, sad, and irritable). Items were scored on a 0-100 VAS-scale (ranging from very little to very much). In addition, participants wore two light sensors (Dimesimeter), one on their indoor clothes and one on their jacket. Wear-time of each sensor was derived from a build-in accelerometer. Light was sampled every minute for one week. Participants received a designated Android smartphone for the duration of EMA. Detailed information on data processing and analysis can be found in @Lindert2018. On average, 80% of the prompts contained valid data. People with insomnia disorder (n = 17) had significantly lower subjective Liking and Wanting than matched controls without sleep complaints (n = 18). This was most apparent at low environmental light intensity. There were no overall differences between groups in Positive mood and Negative mood. Participants with insomnia did have a different diurnal profile of Positive mood and Negative mood [@Lindert2018]. The one-item Karolinska sleepiness scale is advised as a simple way to measure sleepiness in EMA. The item was validated against performance and EEG variables [@kaida2006].
| **Platform(s) used**| Philips Actiwatch Spectrum; Microelectromechanical accelerometer (Move II, Movisens GmbH) | 
| **Contact** | http://research.vumc.nl/en/persons/eus-jw-van-someren|
|             | http://herseninstituut.nl/over-ons/de-organisatie/medewerkers/bart-te-lindert/ |
|             | http://herseninstituut.nl/over-ons/de-organisatie/medewerkers/wisse-van-der-meijden/ |


## Ambulatory Assessment

### De Geus
\index{VU-AMS}

*Prof. dr. Eco de Geus* is head of the department of Biological Psychology and co-director of the Netherlands Twin Registry at the VU University. De Geus has been the driving force behind the development of the VU University Ambulatory Monitoring System (VU-AMS; http://www.vu-ams.nl/vu-ams/), a non-invasive wearable device that is used for continuous ambulatory measurement of the autonomic nervous system.

| Aspect         | Description                                                  | 
|:---------------|:-------------------------------------------------------------|
| **Team** | Eco de Geus, PhD; Gonneke Willemsen, PhD; Martin Gevonden, PhD; Denise van der Mee, MSc, Mandy Tjew-A-Sin, MSc; Cor Stoof, MSc |
| **Organisation** | VU |
| **Project** | VU-AMS was developed at the department of Biological Psychology of the Vrije Universiteit Amsterdam. The system is used worldwide by many research groups, to study stress and emotion in both laboratory and naturalistic settings [@Geus1996]. VU-AMS has been used in the study of ADHD, aggression, anxiety and depressive disorders, mental, social and work-related stress, circadian rhythms, hyperventilation, migraine, sleep, and in studies linking the autonomic nervous system to metabolic and immunological risk factors (see http://www.vu-ams.nl/research/publications/). Current projects include: 
|         | 1)	Validation of a wristwatch-based technology, developed by Philips, to measure skin conductance responses in a laboratory (~2.5 h) and ambulatory (~22h, including the night) setting on a total of 100 subjects (van der Mee et al., ongoing, 2017 - 2021). The goal is to test whether wrist based (Philips) and palm based (VU-AMS) measured skin conductance responses accord, how these measures relate to the heart based measured pre-ejection period (PEP, VU-AMS) and whether it can be related to positive and negative affect (hourly diary prompts). The end goal for the wrist based technology is to detect sympathetic nervous system activity (measured as skin conductance responses) and present this information to the person’s as an index of the current stress level, alongside a one-hour prediction of changes in stress level and cognitive functioning (Cognitive Zone Changes;  http://www.ip.philips.com/licensing/program/121) |
|         | 2)	Ambulatory study on self-regulation among youth (Tjew A Sin et al., 2018-2019). This study is conducted at the schools as part of the NeuroLab project. A total of 50 students, will wear the VU-AMS device for approximately 22 hours. Autonomic nervous system activity is collected continuously over the course of a regular school day (including the night and morning thereafter) and will be related to multiple components of self-regulation, including emotion-regulation, cognitive functioning, impulsivity and inhibition  |
| **EMA measures** | The VU-AMS device is a battery powered wearable that can record 24 to 48 hours of data (4GB storage). It measures the electrocardiogram, the impedance cardiogram, and skin conductance. With VU-AMS, the following outcomes can be collected: Heart Rate / Inter beat Interval (IBI), Heart Rate Variability (SDNN, RMSSD, IBI power spectrum: HF, LF), Respiratory Sinus Arrhythmia (RSA), Pre-Ejection Period (PEP), T-wave amplitude (TWA), Left Ventricular Ejection Time (LVET), Stroke Volume (SV) and Cardiac Output (CO), Respiration Rate (RR), Skin Conductance Level (SCL) and Skin Conductance Responses (SCRs), Movement (Hip-worn tri-axial accelerometer signals (g). |
|                 | The freely available Data Analysis and Management System (DAMS) package is used for  extraction and processing of VU-AMS data (http://www.vu-ams.nl/support/downloads/software/). The DAMS tool offers options for data inspection (visual inspection of raw data), automated detection of R-peaks in raw ECG signal and visual inspection of final IBI time series, event/diary-based data labeling, IBI spectral power calculation, automated scoring of RR, RSA, and PEP form the combined ECG 
| **Platform(s) used** | VU-AMS / DAMS (see also Chapter \@ref(ema-instruments-catalogue)|  
| **Contact** | http://research.vu.nl/en/persons/jcn-de-geus |
|             | http://research.vu.nl/en/persons/ahm-willemsen | 
|             | http://research.vu.nl/en/persons/martin-gevonden |
